import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Dumbbell Set",
    description: "Set of adjustable dumbbells ranging from 5-25kg",
    price: 199.99,
    category: "weights",
    image: "/TwistDumbbell.webp",
    isNew: true,
    date: "2023-05-15",
  },
  {
    id: "2",
    name: "Yoga Mat Pro",
    description: "Non-slip, eco-friendly yoga mat with alignment lines",
    price: 49.99,
    category: "accessories",
    image: "/Non-slip-eco-friendly-yoga-mat-with-alignment-lines.jpg",
    isNew: false,
    date: "2023-02-10",
  },
  {
    id: "3",
    name: "Treadmill T-800",
    description:
      "Foldable treadmill with 15 incline levels and heart rate monitor",
    price: 899.99,
    category: "cardio",
    image: "/Heart-rate-monitor-treadmills.webp",
    isNew: true,
    date: "2023-06-20",
  },
  {
    id: "4",
    name: "Resistance Bands Set",
    description: "Set of 5 resistance bands with different tension levels",
    price: 29.99,
    category: "accessories",
    image: "/black-resistancebands-new-1.webp",
    isNew: false,
    date: "2023-01-05",
  },
  {
    id: "5",
    name: "Olympic Barbell",
    description: "20kg Olympic barbell with knurled grip",
    price: 149.99,
    category: "weights",
    image: "/olympicbarbell.jpg",
    isNew: false,
    date: "2023-03-12",
  },
  {
    id: "6",
    name: "Kettlebell Set",
    description: "Set of 3 cast iron kettlebells (8kg, 12kg, 16kg)",
    price: 119.99,
    category: "weights",
    image: "/kettlebell-set.jpg",
    isNew: false,
    date: "2023-04-18",
  },
  {
    id: "7",
    name: "Exercise Bike",
    description:
      "Stationary bike with adjustable resistance and digital display",
    price: 349.99,
    category: "cardio",
    image: "/exercise-bike.jpg",
    isNew: true,
    date: "2023-06-05",
  },
  {
    id: "8",
    name: "Foam Roller",
    description: "High-density foam roller for muscle recovery",
    price: 24.99,
    category: "accessories",
    image: "/textured-foam-roller.jpg",
    isNew: false,
    date: "2023-02-28",
  },
  {
    id: "9",
    name: "Weight Bench",
    description: "Adjustable weight bench for various exercises",
    price: 179.99,
    category: "weights",
    image: "/Adjustable-weight-bench.jpg",
    isNew: false,
    date: "2023-03-25",
  },
  {
    id: "10",
    name: "Jump Rope",
    description: "Adjustable speed jump rope with ball bearings",
    price: 19.99,
    category: "accessories",
    image: "/Adjustable-jump-rope.jpg",
    isNew: false,
    date: "2023-01-15",
  },
  {
    id: "11",
    name: "Rowing Machine",
    description: "Magnetic resistance rowing machine with LCD monitor",
    price: 499.99,
    category: "cardio",
    image: "/resistance-rowing-machine.jpg",
    isNew: false,
    date: "2023-05-02",
  },
  {
    id: "12",
    name: "Weight Plates Set",
    description: "Set of rubber-coated weight plates (2x5kg, 2x10kg, 2x15kg)",
    price: 249.99,
    category: "weights",
    image: "/Weight-Plates-Set.jpg",
    isNew: false,
    date: "2023-04-10",
  },
];
